=== danielsureda-bot/TASQUES-LMG/tasca_4.1/cataleg.dtd
<!ELEMENT cataleg (single | album)+>

<!ELEMENT single (titol, descripcio?, pais, idioma, genere*, grup, membres, durada)>
<!ATTLIST single codi CDATA #REQUIRED>

<!ELEMENT album (titol, descripcio?, pais, idioma, genere*, grup, membres, numero_cancons, titols_cancons)>
<!ATTLIST album codi CDATA #REQUIRED>

<!ELEMENT titol (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>

<!ELEMENT genere (classica | jazz | blues | gospel | soul | pop | rocknroll | country)>
<!ELEMENT classica EMPTY>
<!ELEMENT jazz EMPTY>
<!ELEMENT blues EMPTY>
<!ELEMENT gospel EMPTY>
<!ELEMENT soul EMPTY>
<!ELEMENT pop EMPTY>
<!ELEMENT rocknroll EMPTY>
<!ELEMENT country EMPTY>

<!ELEMENT grup (#PCDATA)>

<!ELEMENT membres (membre+)>
<!ELEMENT membre (nom)>
<!ATTLIST membre sexe (home | dona) #REQUIRED>
<!ELEMENT nom (#PCDATA)>

<!ELEMENT durada (#PCDATA)> <!ELEMENT numero_cancons (#PCDATA)> <!ELEMENT titols_cancons (canco+)>
<!ELEMENT canco (titol_canco, durada_canco)>
<!ATTLIST canco numero CDATA #REQUIRED>
<!ELEMENT titol_canco (#PCDATA)>
<!ELEMENT durada_canco (#PCDATA)>

=== danielsureda-bot/TASQUES-LMG/tasca_4.1/cataleg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cataleg SYSTEM "cataleg.dtd">
<cataleg>
    <single codi="S001">
        <titol>Single de Prueba</titol>
        <descripcio>Una descripción opcional</descripcio>
        <pais>España</pais>
        <idioma>Castellano</idioma>
        <genere><pop/></genere>
        <grup>Los Programadores</grup>
        <membres>
            <membre sexe="home">
                <nom>Juan Pérez</nom>
            </membre>
        </membres>
        <durada>3:45</durada>
    </single>

    <album codi="A001">
        <titol>Disco de Oro</titol>
        <pais>USA</pais>
        <idioma>Inglés</idioma>
        <genere><jazz/></genere>
        <grup>The Coders</grup>
        <membres>
            <membre sexe="dona">
                <nom>Marta García</nom>
            </membre>
            <membre sexe="home">
                <nom>Alex Smith</nom>
            </membre>
        </membres>
        <numero_cancons>2</numero_cancons>
        <titols_cancons>
            <canco numero="1">
                <titol_canco>Hola Mundo</titol_canco>
                <durada_canco>4:20</durada_canco>
            </canco>
            <canco numero="2">
                <titol_canco>Loop Infinito</titol_canco>
                <durada_canco>3:15</durada_canco>
            </canco>
        </titols_cancons>
    </album>
</cataleg>
